// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6UcT4r7r41gUP2vzCzinSs7SehxDpfck',
    appId: '1:31127704596:web:7994354ee272d34d878301',
    messagingSenderId: '31127704596',
    projectId: 'liveasy-52d70',
    authDomain: 'liveasy-52d70.firebaseapp.com',
    storageBucket: 'liveasy-52d70.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZpyLSyncblG8kHF79X7P5N5rpjcCPNj0',
    appId: '1:31127704596:android:ad67bc13651bceb9878301',
    messagingSenderId: '31127704596',
    projectId: 'liveasy-52d70',
    storageBucket: 'liveasy-52d70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcGOBlm_tkfPNbju3HlN8My2SO-XSQE1w',
    appId: '1:31127704596:ios:a941744dc8d4b46e878301',
    messagingSenderId: '31127704596',
    projectId: 'liveasy-52d70',
    storageBucket: 'liveasy-52d70.appspot.com',
    iosClientId: '31127704596-17mc3jcvbcnn880r38k6dhcv191st3re.apps.googleusercontent.com',
    iosBundleId: 'com.example.liveasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcGOBlm_tkfPNbju3HlN8My2SO-XSQE1w',
    appId: '1:31127704596:ios:c9da4dfb151c3dc5878301',
    messagingSenderId: '31127704596',
    projectId: 'liveasy-52d70',
    storageBucket: 'liveasy-52d70.appspot.com',
    iosClientId: '31127704596-avkaaf06ce3lrk6db5p9j6h1qh171sfh.apps.googleusercontent.com',
    iosBundleId: 'com.example.liveasy.RunnerTests',
  );
}
